### ISSUE TITLE
Requiring watir-webdriver on Travis: undefined method `col_span' for class `Watir::TableCell' (NameError)

### ISSUE THREAD

**Issue by soumyaray** [watir/watir-webdriver#430]
I'm running local tests using watir-webdriver and it works just fine 👍 

To run the same tests on Travis-CI, I'm [setting up xvfb as recommended](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI).

However, when the build commences on Travis, the line `require 'watir-webdriver'` fails with the following error:

```
/home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/table_cell.rb:6:in `alias_method': undefined method `col_span' for class `Watir::TableCell' (NameError)
	from /home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/table_cell.rb:6:in `<class:TableCell>'
	from /home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/table_cell.rb:2:in `<module:Watir>'
	from /home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/table_cell.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver.rb:110:in `require'
	from /home/travis/.rvm/gems/ruby-head/gems/watir-webdriver-0.9.1/lib/watir-webdriver.rb:110:in `<top (required)>'
	from /home/travis/build/ISS-SOA/Codecademy-Ruby/lib/codebadges/badges.rb:3:in `require'
```

Could this an issue with Watir or is something possibly not setup correctly on my Travis build?

**Comment by p0deje** [comment]
Not sure why this happens. Can you give more information like Ruby version, Gemfile you use and how you require watir-webdriver.

**Comment by soumyaray** [comment]
@p0deje - your comment made me realize I wasn't explicitly checking the version number on Travis. I had setup travis to install ruby-head thinking it would be Ruby 2.3.1, but its actually at 2.4.0-dev and that was failing.  It works on Travis with Ruby 2.3.1.  It might still be worth seeing why its failing on 2.4.0-dev. 

Thanks for your help!

**Comment by madhuri03** [comment]
I am getting the same issue with ruby version 2.6.1.

**Comment by titusfortner** [comment]
@madhuri03 can you verify that you do not have any reference to `watir-webdriver` in your gemfile.lock? (everything should be referring to `watir`, and also verify the version of Watir you are using.
